### ISSUE TITLE
Unable to Deploy to Heroku

### ISSUE THREAD

**Issue by mhenry** [diowa/ruby2-rails4-bootstrap-heroku#5]
The [Deploy to Heroku](https://heroku.com/deploy) button doesn't work because `the addon "pgbackups" does not exist.` This might have to do with the [deprecation of PG Backups as an add-on](https://devcenter.heroku.com/changelog-items/623). Removing `"pgbackups:auto-month"` from [app.json](https://github.com/diowa/ruby2-rails4-bootstrap-heroku/blob/master/app.json) should fix the issue.

**Comment by tagliala** [comment]
Thanks for reporting this

Is there a way to schedule backups via `app.json`?

**Comment by mhenry** [comment]
You actually should also rename `newrelic:stark

**Comment by mhenry** [comment]
For your `app.json`, I believe you can add a [post-deploy script](https://devcenter.heroku.com/articles/app-json-schema#scripts) and execute something along the lines of [`heroku pg:backups schedule`](https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups). You'll want to test my theory though.

**Comment by tagliala** [comment]
It should be fixed now, let me know
